# Generated by Django 3.1.7 on 2022-02-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subscription', models.DecimalField(decimal_places=2, max_digits=50)),
                ('redemption', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
